# Generated by Django 2.0.6 on 2018-07-10 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseOfInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_of_injury', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cause of injury',
                'verbose_name_plural': 'Cause of injuries',
                'db_table': 'injuries_causeofinjury',
            },
        ),
        migrations.CreateModel(
            name='ContactCollison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_collision', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact/Collision',
                'verbose_name_plural': 'Contacts/Collisions',
                'db_table': 'injuries_contactcollison',
            },
        ),
        migrations.CreateModel(
            name='InjuredBodyPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injured_body_part', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Injured body part',
                'verbose_name_plural': 'Injured body parts',
                'db_table': 'injuries_injuredbodypart',
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_injury', models.DateField(default=datetime.date.today, verbose_name='Date of injury')),
                ('date_of_return', models.DateField(default=datetime.date.today, verbose_name='Date of return')),
                ('update', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Player')),
                ('cause_of_injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.CauseOfInjury')),
                ('contact_collision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.ContactCollison', verbose_name='Contact/Collison')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('injured_body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.InjuredBodyPart')),
            ],
            options={
                'verbose_name': 'Injury',
                'verbose_name_plural': 'Injuries',
                'db_table': 'injuries_injury',
                'ordering': ['-date_of_injury'],
            },
        ),
        migrations.CreateModel(
            name='LeftRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_right', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Left/Right',
                'verbose_name_plural': 'Right/Left',
                'db_table': 'injuries_leftright',
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mechnism',
                'verbose_name_plural': 'Mechnisms',
                'db_table': 'injuries_mechanism',
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participate', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participation',
                'db_table': 'injuries_participate',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_injury', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Place of injury',
                'verbose_name_plural': 'places of injury',
                'db_table': 'injuries_placeofinjury',
            },
        ),
        migrations.CreateModel(
            name='TypeOfInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_injury', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Type of injuriy',
                'verbose_name_plural': 'Type of injuries',
                'db_table': 'injuries_typeofinjury',
            },
        ),
        migrations.CreateModel(
            name='WhereItHappened',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where_it_happened', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Where it happened',
                'verbose_name_plural': 'Where it happened',
                'db_table': 'injuries_whereithappened',
            },
        ),
        migrations.AddField(
            model_name='injury',
            name='left_right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.LeftRight', verbose_name='Left/Right'),
        ),
        migrations.AddField(
            model_name='injury',
            name='mechanism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.Mechanism'),
        ),
        migrations.AddField(
            model_name='injury',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.Participate'),
        ),
        migrations.AddField(
            model_name='injury',
            name='place_of_injury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.PlaceOfInjury'),
        ),
        migrations.AddField(
            model_name='injury',
            name='type_of_injury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.TypeOfInjury'),
        ),
        migrations.AddField(
            model_name='injury',
            name='where_it_happened',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injuries.WhereItHappened'),
        ),
    ]
